- hosts: all

  roles:
    - role: gantsign.oh-my-zsh
      users: 
        - username: "{{ ansible_env.USER }}"
    - role: geerlingguy.docker
      become: yes

    - role: gantsign.visual-studio-code

  tasks:
    - name: gitの設定
      become: yes
      apt: name=git state=latest
    - git_config: name=core.pager scope=global value="less -R -F -X"
    - git_config: name=user.name scope=global value="tilt-silvie"
    - git_config: name=user.email scope=global value="tilt.silvie@gmail.com"
    - git_config: name=color.ui scope=global value=true
    - git_config: name=core.editor scope=global value="vim -c 'set fenc=utf-8'"
    - git_config: name=color.status scope=global value=auto
    - git_config: name=color.branch scope=global value=auto

    - name: install neovim
      become: yes
      apt:
        name: neovim
        update_cache: yes
        state: latest

    - name: create neovim config directory
      file:
        path: ~/.config/nvim
        state: directory
        mode: 0755

    - name: create neovim conf file symlink
      file: 
        src: ~/my-devenv/dotfiles/.vimrc 
        dest: ~/.config/nvim/init.vim
        state: link

    - name: get dein(vim plugin manager)
      get_url:
        url: https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh
        dest: /tmp/installer.sh

    - name: install dein
      script: /tmp/installer.sh ~/.cache/dein

    - name: update neovim-python client (for remove warning when nvim launched with deocomplete)
      shell: pip3 install neovim --upgrade

    - name: install curl
      become: yes
      apt:
        name: curl
        state: latest

    - name: install byobu
      become: yes
      apt:
        name: byobu
        state: latest

    - name: ホームディレクトリ以下のディレクトリ名を日本語から英語にする
      shell: LANG=C xdg-user-dirs-update --force

    - name: ホームディレクトリ以下に残った日本語ディレクトリを削除する
      file: path={{ item }} state=absent
      with_items:
        - ~/ダウンロード
        - ~/テンプレート
        - ~/デスクトップ
        - ~/ドキュメント
        - ~/ビデオ
        - ~/ピクチャ
        - ~/ミュージック
        - ~/公開
    
    - name: remove ~/.zshrc which was created by oh-my-zsh
      file: path=~/.zshrc state=absent

    - name: dotfilesのシンボリックリンクを作成
      file: src=~/my-devenv/dotfiles/.vimrc dest=~/.vimrc state=link
      file: src=~/my-devenv/dotfiles/.zshrc dest=~/.zshrc state=link
