- hosts: all
  remote_user: ishikura
  tasks:
    - name: ツール群をインストール
      become: yes
      apt: name={{ item }} state=installed
      with_items:
        - git
        - neovim  
        - zsh
        - curl

    - name: oh-my-zshをインストール
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

    - name: ホームディレクトリ以下のディレクトリ名を日本語から英語にする
      shell: LANG=C xdg-user-dirs-update --force

    - name: ホームディレクトリ以下に残った日本語ディレクトリを削除する
      file: path={{ item }} state=absent
      with_items:
        - ~/ダウンロード
        - ~/テンプレート
        - ~/デスクトップ
        - ~/ドキュメント
        - ~/ビデオ
        - ~/ピクチャ
        - ~/ミュージック
        - ~/公開

    - name: このリポジトリをホームディレクトリ以下に配置
      git: 
        repo: 'https://github.com/tilt-silvie/my-devenv'
        dest: ~/my-devenv

    - name: dotfilesのシンボリックリンクを作成
      file: src=~/my-devenv/dotfiles/.vimrc dest=~/.vimrc state=link

    - name: gitの設定
      shell: "{{ item }}"
      with_items:
        - git config --global user.email "tilt.silvie@gmail.com"
        - git config --global user.name "Makito Ishikura"
        - git config --global core.editor 'vim -c "set fenc=utf-8"'
        - git config --global color.diff auto
        - git config --global color.status auto
        - git config --global color.branch auto


    - name: dockerのアンインストール
      become: yes
      ignore_errors: yes
      apt: 
        name: "{{ packages }}"
      state: absent
      update_cache: yes
      vars:
        packages:
        - docker 
        - docker-engine
        - docker.io

    - name: docker関連パッケージのインストール
      become: yes
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: dockerリポジトリ鍵の登録
      become: yes
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

    - name: dockerリポジトリの登録
      become: yes
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    - name: dockerインストール
      become: yes
      apt:
        name: docker-ce
        update_cache: yes

