- hosts: all
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  tasks:
    - name: ツール群をインストール
      apt: name={{ item }} state=installed
      with_items:
        - neovim  
        - zsh
        - curl

    - name: gitの設定
      apt: name=git state=latest
    - git_config: name=user.name scope=global value="Makito Ishikura"
    - git_config: name=user.email scope=global value="tilt.silvie@gail.com"
    - git_config: name=color.ui scope=global value=true
    - git_config: name=core.editor scope=global value="vim -c 'set fenc=utf-8'"
    - git_config: name=color.status scope=global value=auto
    - git_config: name=color.branch scope=global value=auto

    - name: oh-my-zshをインストール
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

    - name: ホームディレクトリ以下のディレクトリ名を日本語から英語にする
      shell: LANG=C xdg-user-dirs-update --force

    - name: ホームディレクトリ以下に残った日本語ディレクトリを削除する
      file: path={{ item }} state=absent
      with_items:
        - ~/ダウンロード
        - ~/テンプレート
        - ~/デスクトップ
        - ~/ドキュメント
        - ~/ビデオ
        - ~/ピクチャ
        - ~/ミュージック
        - ~/公開

    - name: dotfilesのシンボリックリンクを作成
      file: src=~/my-devenv/dotfiles/.vimrc dest=~/.vimrc state=link

    - name: dockerのアンインストール
      ignore_errors: yes
      apt: 
        name: "{{ packages }}"
      state: absent
      update_cache: yes
      vars:
        packages:
        - docker 
        - docker-engine
        - docker.io

    - name: docker関連パッケージのインストール
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: dockerリポジトリ鍵の登録
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

    - name: dockerリポジトリの登録
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    - name: dockerインストール
      apt:
        name: docker-ce
        update_cache: yes

